server:
  port: 8088

spring:
  application:
    name: auction-api
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5430/auctionDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5430/auctionDB
    user: postgres
    password: postgres
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true