CREATE TABLE AUCTION_QUESTIONS
(
    ID       BIGSERIAL,
    QUESTION VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE AUCTION_ANSWERS_CHOICES
(
    ID          BIGSERIAL,
    CHOICE      VARCHAR(255),
    QUESTION_ID BIGINT REFERENCES AUCTION_QUESTIONS (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE AUCTION_ITEMS
(
    ID                BIGSERIAL,
    AUCTION_ITEM_TEXT  TEXT,
    PRIMARY KEY (ID)
);

CREATE TABLE BIDDERS
(
    ID              BIGSERIAL,
    USERNAME        VARCHAR(255),
    NAME            VARCHAR(255),
    PRESENT         VARCHAR(255),
    AUCTION_ITEM_ID BIGINT REFERENCES AUCTION_ITEMS (ID) ON DELETE CASCADE,
    PRIMARY KEY (ID)
);

CREATE TABLE AUCTION_ANSWERS
(
    ID          BIGSERIAL,
    BIDDER_ID    BIGINT REFERENCES BIDDERS (ID),
    QUESTION_ID BIGINT REFERENCES AUCTION_QUESTIONS (ID),
    ANSWER      VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE AUCTION_RELATIONSHIPS
(
    ID                BIGSERIAL,
    SOURCE_BIDDER_ID  BIGINT REFERENCES BIDDERS (ID),
    TARGET_BIDDER_ID  BIGINT REFERENCES BIDDERS (ID)
);